### ISSUE TITLE
Где взять такой же баннер

### ISSUE THREAD

**Issue by fedorovvvv** [Slizzygod/Slizzygod#1]
Слишком уж он царский

**Comment by Slizzygod** [comment]
Задизайнить. Я сам дизайнил сидел

**Comment by fedorovvvv** [comment]
Не такую я реакцию ожидал)
Ты как там? 2 года не виделись (а может и больше)

**Comment by Slizzygod** [comment]
@fedorovvvv а какую?) Да уже больше прошло. Скучаешь? Я тружусь в поте лица. Ты как? У вас последний год или еще? Я уже запутался :D

**Comment by Slizzygod** [comment]
@fedorovvvv могу поделиться на дизайн банера в фигме, если надо.
